name = "PaperMod"
description = "A fast, clean, responsive theme ported to Zola."
license = "MIT"
homepage = "https://github.com/cydave/zola-theme-papermod"
min_version = "0.4.0"
demo = "https://cydave.github.io/zola-theme-papermod/"

[extra]
# Refer to provided config.toml; [extra.papermod]

[author]
name = "cydave"
homepage = "https://github.com/cydave"

[original]
author = "Aditya Telange"
homepage = "https://github.com/adityatelange"
repo = "https://github.com/adityatelange/hugo-PaperMod"
